

name="python is easy to understand" #find
print("*****************************************************")
print(name.find("easy"))

print(name.find("cherry"))#the character not present return -1(False)
print(name.find("understand"))
print(name.find("p"))
print(name.find("thon"))
print(name.find("n"))
print(name.find(""))
print("****************************************************")
#rfind()
print(name.rfind("easy"))
print(name.rfind("s"))
print(name.rfind("t"))
print(name.rfind("krishna"))#the character not present return -1(False)
print(name.rfind("y"))
print(name.rfind("a"))
print(name.rfind("t"))
print("*****************************************************")
#rindex()
print(name.index("easy"))
print(name.index("is"))
# print(name.index("krishna"))  #ValueError: substring not found--(the character not present return -1(False))
print(name.index("to"))
print(name.index("understand"))
print(name.index("p"))
print(name.index("thon"))
print(name.index(""))

print("***********************************************")
#Find Method syntax
#find(substring,statrt_index,end_index)
print(name.find("easy",10,15))
print(name.find("krishna",10,14)) #the character not present return -1(False)
print(name.find("understand",1,10))#the character not present return -1(False)
print(name.find("is",0,9))
print(name.find("",0,10))
print(name.find("ton",5,11))#the character not present return -1(False)
print(name.find("python",0,9))
print("*********************************************************")

#rindex()
print(name.rindex("python"))
print(name.rindex("easy"))
print(name.rindex("to"))
print(name.rindex("s"))
print(name.rindex("n"))
print(name.rindex("u"))
print(name.rindex("d"))


